### ISSUE TITLE
IllegalStateException: Expected BEGIN_OBJECT but was NAME

### ISSUE THREAD

**Issue by shostko** [MaximKirko/training_2017_android#1]
> E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 5 columns.
> E/IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
> E/AndroidRuntime: FATAL EXCEPTION: IntentService[FriendsDataDownloadService]
> Process: com.github.maximkirko.training_2017_android_sprint2, PID: 9974
> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NAME
>     at android.util.JsonReader.expect(JsonReader.java:310)
>     at android.util.JsonReader.beginObject(JsonReader.java:293)
>     at com.github.maximkirko.training_2017_android.reader.UserJSONReader.readUser(UserJSONReader.java:80)
>     at com.github.maximkirko.training_2017_android.reader.UserJSONReader.readUsersArray(UserJSONReader.java:66)
>     at com.github.maximkirko.training_2017_android.reader.UserJSONReader.readToList(UserJSONReader.java:48)
>     at com.github.maximkirko.training_2017_android.service.FriendsDataDownloadService.getDataFromJson(FriendsDataDownloadService.java:29)
>     at com.github.maximkirko.training_2017_android.service.FriendsDataDownloadService.getDataFromJson(FriendsDataDownloadService.java:14)
>     at com.github.maximkirko.training_2017_android.service.VKRequestAbstractService.getDataFromNetwork(VKRequestAbstractService.java:54)
>     at com.github.maximkirko.training_2017_android.service.VKRequestAbstractService.onHandleIntent(VKRequestAbstractService.java:41)
>     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
>     at android.os.Handler.dispatchMessage(Handler.java:102)
>     at android.os.Looper.loop(Looper.java:154)
>     at android.os.HandlerThread.run(HandlerThread.java:61)
>

**Comment by shostko** [comment]
[logs-kirko.txt](https://github.com/MaximKirko/training_2017_android/files/850173/logs-kirko.txt)
